# Generated by Django 2.2.12 on 2020-08-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('slug', models.SlugField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
